-- @Autores       J. Miguel Arroyo Quiroz, Arturo Perez Quintana
-- @Fecha         13/12/2023
-- @Descripcion   Creación de las tablas para la base de datos del proyecto

whenever sqlerror exit rollback;

CREATE TABLE CATEGORIA(
    CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(40)     NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (CATEGORIA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE USUARIO(
    USUARIO_ID       NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    AP_PATERNO       VARCHAR2(40)     NOT NULL,
    AP_MATERNO       VARCHAR2(40)     NOT NULL,
    NOMBRE_USUARO    VARCHAR2(30)     NOT NULL,
    CONTRASENIA      VARCHAR2(40)     NOT NULL,
    EMAIL            VARCHAR2(40)     NOT NULL,
    FECHA_REG        DATE DEFAULT SYSDATE NOT NULL,
    FOTO             BLOB             NOT NULL
    TABLESPACE USUARIOS_BLOB_TBS,
    RFC              VARCHAR2(13)     NOT NULL,
    ES_VENDEDOR      CHAR(1)          NOT NULL,
    ES_COMPRADOR     CHAR(1)          NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONTRAINT USUARIO_RFC_UK UNIQUE (RFC)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE OCUPACION(
    OCUPACION_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (OCUPACION_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TABLAS_TBS;


CREATE TABLE COMPRADOR(
    COMPRADOR_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPCION     VARCHAR2(100)    NOT NULL,
    CELULAR         NUMBER(13, 0)    NOT NULL,
    OCUPACION_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT COMPRADOR_PK PRIMARY KEY (COMPRADOR_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS, 
    CONSTRAINT COMPRADOR_USUARIO_COMPRADOR_ID_FK FOREIGN KEY (COMPRADOR_ID)
    REFERENCES USUARIO(USUARIO_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS,
    CONSTRAINT OCUPACION_OCUPACION_ID_FK FOREIGN KEY (OCUPACION_ID)
    REFERENCES OCUPACION(OCUPACION_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TABLAS_TBS;


CREATE TABLE VENDEDOR(
    VENDEDOR_ID     NUMBER(10, 0)    NOT NULL,
    TIPO            VARCHAR2(20)     NOT NULL,
    DIRECCION       VARCHAR2(200)    NOT NULL,
    CALIFICACION    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT VENDEDOR_PK PRIMARY KEY (VENDEDOR_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS, 
    CONSTRAINT VENDEDOR_VENDEDOR_ID_FK FOREIGN KEY (VENDEDOR_ID)
    REFERENCES USUARIO(USUARIO_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TABLAS_TBS;


CREATE TABLE TARJETA(
    TARJETA_ID      NUMBER(10, 0)    NOT NULL,
    COMPRADOR_ID    NUMBER(10, 0)    NOT NULL,
    NUM_TARJETA     VARCHAR2(16)     NOT NULL,
    BANCO           VARCHAR2(40)     NOT NULL,
    ANIO            VARCHAR2(2)      NOT NULL,
    MES             VARCHAR2(2)      NOT NULL,
    CVV             VARCHAR2(3)      NOT NULL,
    CONSTRAINT TARJETA_PK PRIMARY KEY (TARJETA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS, 
    CONSTRAINT TARJETA_TARJETA_ID_FK FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TARJETAS_TBS;


CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    FORMA_PAGO           CHAR(1)          NOT NULL,
    DIRECCION_ENTREGA    VARCHAR2(200)    NOT NULL,
    FECHA_ORDEN          DATE DEFAULT SYSDATE NOT NULL,
    PAGO_EXITOSO         CHAR(1)          NOT NULL,
    TARJETA_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ORDEN_COMPRA_PK PRIMARY KEY (ORDEN_COMPRA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS, 
    CONSTRAINT TARJETA_TARJETA_ID_FK FOREIGN KEY (TARJETA_ID)
    REFERENCES TARJETA(TARJETA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TABLAS_TBS;


CREATE TABLE STATUS_PRODUCTO(
    STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE                 VARCHAR2(20),
    DESCRIPCION           VARCHAR2(100),
    CONSTRAINT STATUS_PRODUCTO_PK PRIMARY KEY (STATUS_PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE PRODUCTO(
    PRODUCTO_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(40)     NOT NULL,
    DESCRIPCION             VARCHAR2(500)    NOT NULL,
    DESCRIPCION_DEFECTOS    VARCHAR2(500),
    FECHA_VIDA_UTIL         DATE             NOT NULL,
    PRECIO_INICIAL          NUMBER(10, 2)    NOT NULL,
    VENDEDOR_ID             NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID         NUMBER(10, 0),
    STATUS_PRODUCTO_ID      NUMBER(10, 0)    NOT NULL,
    CATEGORIA_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS, 
    CONSTRAINT VENDEDOR_VENDEDOR_ID_FK FOREIGN KEY (VENDEDOR_ID)
    REFERENCES VENDEDOR(VENDEDOR_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT ORDEN_COMPRA_ORDEN_COMPRA_ID_FK FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT STATUS_PRODUCTO_STATUS_PRODUCTO_ID_FK FOREIGN KEY (STATUS_PRODUCTO_ID)
    REFERENCES STATUS_PRODUCTO(STATUS_PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT CATEGORIA_CATEGORIA_ID_FK FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA(CATEGORIA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE EVALUACION_PRODUCTO(
    EVALUACION_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    EVALUACION_VENDEDOR       CHAR(1)          NOT NULL,
    COMENTARIO_PRODUCTO       VARCHAR2(300),
    COMPRADOR_ID              NUMBER(10, 0)    NOT NULL,
    PRODUCTO_ID               NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EVALUACION_PRODUCTO_PK PRIMARY KEY (EVALUACION_PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS, 
    CONSTRAINT COMPRADOR_EVA_PROD_COMPRADOR_ID_FK FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT PROD_EVA_PROD_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE PAQUETERIA(
    PAQUETERIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(20)     NOT NULL,
    CONSTRAINT PAQUETERIA_PK PRIMARY KEY (PAQUETERIA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TABLAS_TBS;


CREATE TABLE FACTURA(
    FACTURA_ID         NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    FOLIO              VARCHAR2(6)      NOT NULL,
    COMISION           NUMBER(10, 2)    NOT NULL,
    PAQUETERIA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT FACTURA_PK PRIMARY KEY (FACTURA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS, 
    CONSTRAINT ORDEN_COMPRA_FAC_ORDEN_COMPRA_ID_FK FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS,
    CONSTRAINT PAQUETERIA_FAC_PAQUETERIA_ID_FK FOREIGN KEY (PAQUETERIA_ID)
    REFERENCES PAQUETERIA(PAQUETERIA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_TABLAS_TBS;


CREATE TABLE GALERIA(
    GALERIA_ID     NUMBER(10, 0)    NOT NULL,
    ARCHIVO        BLOB             NOT NULL
    TABLESPACE SUBASTAS_BLOB_TBS,
    PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT GALERIA_PK PRIMARY KEY (GALERIA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS, 
    CONSTRAINT PRODUCTO_GAL_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE HISTORICO_STATUS_PRODUCTO(
    HISTORICO_STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                    DATE DEFAULT SYSDATE NOT NULL,
    PRODUCTO_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_PRODUCTO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_PRODUCTO_PK PRIMARY KEY (HISTORICO_STATUS_PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS, 
    CONSTRAINT PRODUCTO_HISTORICO_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT STATUS_PROD_HIS_PROD_STATUS_PROD_ID_FK FOREIGN KEY (STATUS_PRODUCTO_ID)
    REFERENCES STATUS_PRODUCTO(STATUS_PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE MONITOREO(
    MONITOREO_ID       NUMBER(10, 0)    NOT NULL,
    LATITUD            NUMBER(10, 6)    NOT NULL,
    LONGITUD           NUMBER(10, 6)    NOT NULL,
    ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT MONITOREO_PK PRIMARY KEY (MONITOREO_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS, 
    CONSTRAINT ORDEN_COMPRA_MONIT_ORDEN_COMPRA_ID_FK FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX TABLESPACE USUARIOS_INDICES_TBS
) TABLESPACE USUARIOS_INDICES_TBS;


CREATE TABLE SUBASTA(
    SUBASTA_ID         NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO       TIMESTAMP(6)     NOT NULL,
    FECHA_CIERRE       TIMESTAMP(6)     NOT NULL,
    TOTAL_PRODUCTOS    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT SUBASTA_PK PRIMARY KEY (SUBASTA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;


CREATE TABLE OFERTA(
    OFERTA_ID       NUMBER(10, 0)    NOT NULL,
    FECHA           DATE DEFAULT SYSDATE NOT NULL,
    IMPORTE         NUMBER(10, 2)    NOT NULL,
    ES_GANADORA     CHAR(1)          NOT NULL,
    COMPRADOR_ID    NUMBER(10, 0)    NOT NULL,
    PRODUCTO_ID     NUMBER(10, 0)    NOT NULL,
    SUBASTA_ID      NUMBER(10, 0),
    CONSTRAINT OFERTA_PK PRIMARY KEY (OFERTA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS, 
    CONSTRAINT COMPRADOR_OFERTA_COMPRADOR_ID_FK FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT PROD_OFERTA_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS,
    CONSTRAINT SUBASTA_OFERTA_SUBASTA_ID_FK FOREIGN KEY (SUBASTA_ID)
    REFERENCES SUBASTA(SUBASTA_ID)
    USING INDEX TABLESPACE SUBASTAS_INDICES_TBS
) TABLESPACE SUBASTAS_TABLAS_TBS;