--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      Model_eMarket_v1.2.DM1
-- Author :       pc-apq
--
-- Date Created : Wednesday, December 13, 2023 21:49:11
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CATEGORIA 
--

CREATE TABLE CATEGORIA(
    CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (CATEGORIA_ID)
)
;



-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    USUARIO_ID       NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    AP_PATERNO       VARCHAR2(40)     NOT NULL,
    AP_MATERNO       VARCHAR2(40)     NOT NULL,
    NOMBRE_USUARO    VARCHAR2(30)     NOT NULL,
    CONTRASENIA      VARCHAR2(40)     NOT NULL,
    EMAIL            VARCHAR2(40)     NOT NULL,
    FECHA_REG        DATE             NOT NULL,
    FOTO             BLOB             NOT NULL,
    RFC              VARCHAR2(13)     NOT NULL,
    ES_VENDEDOR      CHAR(1)          NOT NULL,
    ES_COMPRADOR     CHAR(1)          NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (USUARIO_ID)
)
;



-- 
-- TABLE: OCUPACION 
--

CREATE TABLE OCUPACION(
    OCUPACION_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (OCUPACION_ID)
)
;



-- 
-- TABLE: COMPRADOR 
--

CREATE TABLE COMPRADOR(
    COMPRADOR_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPCION     VARCHAR2(100)    NOT NULL,
    CELULAR         NUMBER(13, 0)    NOT NULL,
    OCUPACION_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (COMPRADOR_ID), 
    CONSTRAINT RefUSUARIO111 FOREIGN KEY (COMPRADOR_ID)
    REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT RefOCUPACION291 FOREIGN KEY (OCUPACION_ID)
    REFERENCES OCUPACION(OCUPACION_ID)
)
;



-- 
-- TABLE: VENDEDOR 
--

CREATE TABLE VENDEDOR(
    VENDEDOR_ID     NUMBER(10, 0)    NOT NULL,
    TIPO            VARCHAR2(20)     NOT NULL,
    DIRECCION       VARCHAR2(200)    NOT NULL,
    CALIFICACION    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (VENDEDOR_ID), 
    CONSTRAINT RefUSUARIO91 FOREIGN KEY (VENDEDOR_ID)
    REFERENCES USUARIO(USUARIO_ID)
)
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID      NUMBER(10, 0)    NOT NULL,
    COMPRADOR_ID    NUMBER(10, 0)    NOT NULL,
    NUM_TARJETA     VARCHAR2(16)     NOT NULL,
    BANCO           VARCHAR2(40)     NOT NULL,
    ANIO            VARCHAR2(2)      NOT NULL,
    MES             VARCHAR2(2)      NOT NULL,
    CVV             VARCHAR2(3)      NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (TARJETA_ID), 
    CONSTRAINT RefCOMPRADOR121 FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID)
)
;



-- 
-- TABLE: ORDEN_COMPRA 
--

CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    FORMA_PAGO           CHAR(1)          NOT NULL,
    DIRECCION_ENTREGA    VARCHAR2(200)    NOT NULL,
    FECHA_ORDEN          TIMESTAMP(6)     NOT NULL,
    PAGO_EXITOSO         CHAR(1)          NOT NULL,
    TARJETA_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (ORDEN_COMPRA_ID), 
    CONSTRAINT RefTARJETA351 FOREIGN KEY (TARJETA_ID)
    REFERENCES TARJETA(TARJETA_ID)
)
;



-- 
-- TABLE: STATUS_PRODUCTO 
--

CREATE TABLE STATUS_PRODUCTO(
    STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE                 VARCHAR2(20),
    DESCRIPCION           VARCHAR2(100),
    CONSTRAINT PK6 PRIMARY KEY (STATUS_PRODUCTO_ID)
)
;



-- 
-- TABLE: PRODUCTO 
--

CREATE TABLE PRODUCTO(
    PRODUCTO_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(40)     NOT NULL,
    DESCRIPCION             VARCHAR2(500)    NOT NULL,
    DESCRIPCION_DEFECTOS    VARCHAR2(500),
    FECHA_VIDA_UTIL         TIMESTAMP(6)     NOT NULL,
    PRECIO_INICIAL          NUMBER(10, 2)    NOT NULL,
    VENDEDOR_ID             NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID         NUMBER(10, 0),
    STATUS_PRODUCTO_ID      NUMBER(10, 0)    NOT NULL,
    CATEGORIA_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (PRODUCTO_ID), 
    CONSTRAINT RefVENDEDOR41 FOREIGN KEY (VENDEDOR_ID)
    REFERENCES VENDEDOR(VENDEDOR_ID),
    CONSTRAINT RefORDEN_COMPRA151 FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT RefSTATUS_PRODUCTO251 FOREIGN KEY (STATUS_PRODUCTO_ID)
    REFERENCES STATUS_PRODUCTO(STATUS_PRODUCTO_ID),
    CONSTRAINT RefCATEGORIA301 FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA(CATEGORIA_ID)
)
;



-- 
-- TABLE: EVALUACION_PRODUCTO 
--

CREATE TABLE EVALUACION_PRODUCTO(
    EVALUACION_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    EVALUACION_VENDEDOR       CHAR(1)          NOT NULL,
    COMENTARIO_PRODUCTO       VARCHAR2(300),
    COMPRADOR_ID              NUMBER(10, 0)    NOT NULL,
    PRODUCTO_ID               NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (EVALUACION_PRODUCTO_ID), 
    CONSTRAINT RefCOMPRADOR311 FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID),
    CONSTRAINT RefPRODUCTO321 FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
)
;



-- 
-- TABLE: PAQUETERIA 
--

CREATE TABLE PAQUETERIA(
    PAQUETERIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(20)     NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (PAQUETERIA_ID)
)
;



-- 
-- TABLE: FACTURA 
--

CREATE TABLE FACTURA(
    FACTURA_ID         NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    FOLIO              VARCHAR2(6)      NOT NULL,
    COMISION           NUMBER(10, 2)    NOT NULL,
    PAQUETERIA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (FACTURA_ID), 
    CONSTRAINT RefORDEN_COMPRA241 FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT RefPAQUETERIA281 FOREIGN KEY (PAQUETERIA_ID)
    REFERENCES PAQUETERIA(PAQUETERIA_ID)
)
;



-- 
-- TABLE: GALERIA 
--

CREATE TABLE GALERIA(
    GALERIA_ID     NUMBER(10, 0)    NOT NULL,
    ARCHIVO        BLOB             NOT NULL,
    PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (GALERIA_ID), 
    CONSTRAINT RefPRODUCTO231 FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_PRODUCTO 
--

CREATE TABLE HISTORICO_STATUS_PRODUCTO(
    HISTORICO_STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                    TIMESTAMP(6)     NOT NULL,
    PRODUCTO_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_PRODUCTO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (HISTORICO_STATUS_PRODUCTO_ID), 
    CONSTRAINT RefPRODUCTO261 FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID),
    CONSTRAINT RefSTATUS_PRODUCTO271 FOREIGN KEY (STATUS_PRODUCTO_ID)
    REFERENCES STATUS_PRODUCTO(STATUS_PRODUCTO_ID)
)
;



-- 
-- TABLE: MONITOREO 
--

CREATE TABLE MONITOREO(
    MONITOREO_ID       NUMBER(10, 0)    NOT NULL,
    LATITUD            NUMBER(10, 6)    NOT NULL,
    LONGITUD           NUMBER(10, 6)    NOT NULL,
    ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (MONITOREO_ID), 
    CONSTRAINT RefORDEN_COMPRA361 FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
)
;



-- 
-- TABLE: SUBASTA 
--

CREATE TABLE SUBASTA(
    SUBASTA_ID         NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO       TIMESTAMP(6)     NOT NULL,
    FECHA_CIERRE       TIMESTAMP(6)     NOT NULL,
    TOTAL_PRODUCTOS    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (SUBASTA_ID)
)
;



-- 
-- TABLE: OFERTA 
--

CREATE TABLE OFERTA(
    OFERTA_ID       NUMBER(10, 0)    NOT NULL,
    FECHA           TIMESTAMP(6)     NOT NULL,
    IMPORTE         NUMBER(10, 2)    NOT NULL,
    ES_GANADORA     CHAR(1)          NOT NULL,
    COMPRADOR_ID    NUMBER(10, 0)    NOT NULL,
    PRODUCTO_ID     NUMBER(10, 0)    NOT NULL,
    SUBASTA_ID      NUMBER(10, 0),
    CONSTRAINT PK12 PRIMARY KEY (OFERTA_ID), 
    CONSTRAINT RefCOMPRADOR181 FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID),
    CONSTRAINT RefPRODUCTO211 FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID),
    CONSTRAINT RefSUBASTA221 FOREIGN KEY (SUBASTA_ID)
    REFERENCES SUBASTA(SUBASTA_ID)
)
;



